CREATE TABLE IF NOT EXISTS tags (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '标签 ID',
    name VARCHAR(100) NOT NULL COMMENT '标签名称',
    slug VARCHAR(100) UNIQUE NOT NULL COMMENT '标签别名',
    description TEXT COMMENT '标签描述',
    article_count INT DEFAULT 0 COMMENT '关联文章数量',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文章标签表';