CREATE TABLE IF NOT EXISTS user_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户 ID',
    user_id BIGINT NOT NULL UNIQUE COMMENT '关联 users 表 ID',
    nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
    avatar_url VARCHAR(255) DEFAULT NULL COMMENT '头像 URL',
    bio VARCHAR(500) DEFAULT NULL COMMENT '个人简介',
    birthday DATE DEFAULT NULL COMMENT '生日',
    gender TINYINT DEFAULT 0 COMMENT '性别：0=未知，1=男，2=女',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户资料表';